"""add task reminder lead time

Revision ID: 5552e04fb75a
Revises: b5e6428644a6
Create Date: 2026-08-26 21:13:11.190696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5552e04fb75a'
down_revision: Union[str, Sequence[str], None] = 'b5e6428644a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_minutes_before', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('reminder_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_notified_at')
    op.drop_column('tasks', 'reminder_minutes_before')
    # ### end Alembic commands ###
